### ISSUE TITLE
wstool fails with error when unknown option is given to wstool info --only

### ISSUE THREAD

**Issue by cbandera** [vcstools/wstool#89]
Wstool fails, with error when unknown option is given to `wstool info --only`

```
$ wstool info --only asd
Traceback (most recent call last):
  File "/usr/local/bin/wstool", line 62, in <module>
    sys.exit(wstool.wstool_cli.wstool_main(sys.argv))
  File "/usr/lib/python2.7/dist-packages/wstool/wstool_cli.py", line 180, in wstool_main
    return ws_commands[command](workspace, args)
  File "/usr/lib/python2.7/dist-packages/wstool/multiproject_cli.py", line 1209, in cmd_info
    localnames=args)
  File "/usr/lib/python2.7/dist-packages/wstool/cli_common.py", line 416, in get_info_table_raw_csv
    parser.error("Invalid --only option '%s', valids are %s" %
NameError: global name 'parser' is not defined
```

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #154.
